EXPERIMENT_ROOT_PATH: "./experiments/"
EXPERIMENT_NAME: "your_name"
DEVICE: "cuda"
TRAINING_SETTING:
  TRAIN_DIR_X: "./data/"
  TRAIN_DIR_Y: "./data/"
  NUM_EPOCHS: 100
  LAMBDA_Y: 1
  LEARNING_RATE: 0.00015
  BATCH_SIZE: 1
  NUM_WORKERS: 4
  SAVE_MODEL: true
  SAVE_MODEL_EPOCH_STEP: 1
  VISUALIZATION_STEP: 50
  LOAD_MODEL: false
  LOAD_EPOCH: 0
INFERENCE_SETTING:
  TEST_DIR_X: "./data/"
  MODEL_VERSION: " "
  SAVE_ORIGINAL_IMAGE: False